changelog:
  categories:
    - title: ğŸ’¥ Breaking changes
      labels:
        - breaking-change
    - title: âš¡ï¸Improvements
      labels:
        - enhancement
        - documentation
    - title: ğŸ¨ Other changes
      labels:
        - "*"
